#
# Copyright (C) 2008-2014 The LuCI Team <luci@lists.subsignal.org>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Support for HSO (Option 3G Cards)
LUCI_DEPENDS:=+comgt +kmod-usb-net +kmod-usb-net-hso

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
